### ISSUE TITLE
Branch specific README.md files

### ISSUE THREAD

**Issue by davidhasell** [lagoon-examples/drupal-solr#94]
Thanks for these very helpful lagoon examples! Please could I suggest making them even more helpful by including branch specific hints in the README.md files. For example, this branch could helpfully include the key instructions currently tucked away in a comment in the all.settings.php file:

`### Lagoon Solr connection.
// WARNING: you have to create a search_api server having "solr" machine name at
// /admin/config/search/search-api/add-server to make this work.`

**Comment by tobybellwood** [comment]
fixed in https://github.com/lagoon-examples/drupal-solr/commit/a72f626271a1addbe5f8efe93e83fbab4153f7a0
